openapi: 3.0.0
info:
  title: Acceptors API
  version: 1.0.0
  description: API specification for acceptors resource
servers:
- url: https://api.example.com
paths:
  /api/acceptors:
    servers: []
    post:
      summary: Register an acceptor [Acceptor PSP]
      description: "\nAn acceptor PSP can register one acceptor and up to 50 shops with each request.\n\nThe `acceptorPspId` from the authorisation token will be used to populate the `acceptorPspId` of\
        \ the acceptor resource. \nThis endpoint call does not support partial transactions. Either the entire call succeeds or the entire call fails. If, for example, one shop object contains incomplete\
        \ data, the entire registration will fail and the entire call will have to be repeated after the issue is corrected.\n**\u26A0\uFE0F Advance notice of breaking change**. The fields `websiteUrl`,\
        \ `tacAndRefundPoliciesUrl`, `type` and `state` located inside `shops`, fields `phoneNumber`, `emailAddress` and `contactFormUrl` located inside `customerService`, fields `personEmailAddress` located\
        \ inside `disputesContact` and fields `state`, `qrCodeCallbackUrl` located in the request payload will be subject to a hard limit of specified `maxLength` characters starting 16 July 2026.\n\n##\
        \ Scope \nThis endpoint call requires the `acceptor:management` scope.    "
      operationId: requestRegistration
      security:
      - BearerAccessToken: []
      tags:
      - acceptors
      requestBody:
        content:
          application/hal+json; charset=UTF-8:
            schema:
              $ref: '#/components/schemas/createAcceptorRequest'
            examples:
              Acceptor registration request:
                value:
                  externalId: externalAcceptorId1
                  name: myAcceptorName
                  mcc: '5555'
                  state: Active
                  businessIncorporatedOn: '1995-01-01'
                  marketplace: false
                  address:
                    line1: "Hauptstra\xDFe 1"
                    line2: Floor 1
                    postalCode: '12345'
                    city: Berlin
                    state: Berlin
                    country: DE
                  legal:
                    vatNumber: EU123456789
                    taxNumber: taxNumber
                    registerNumber: registerNumber
                  shops:
                  - externalShopId: f81a8715-29b0-4169-8366-b1a460b59855
                    name: shopName
                    websiteUrl: https://shopName.de
                    type: OnlineShop
                    state: Active
                    logo: data:image/jpeg;base64,/9j/4AAQSkZJRg.....gq8FXgq8FXgq7fmlf//Z
                    tacAndRefundPoliciesUrl: https://shopName.de/terms-and-conditions-and-refunds
                    customerService:
                      emailAddress: customer@shopName.de
                      contactFormUrl: https://shopName.de/contactUs
                      phoneNumber: '+123456789'
                    disputesContact:
                      personName: John Doe
                      personEmailAddress: disputes@shopName.de
                    businessAddress:
                      line1: "Hauptstra\xDFe 1"
                      line2: Floor 1
                      postalCode: '12345'
                      city: Berlin
                      state: Berlin
                      country: DE
                  payfacId: 7ce71496-b604-4954-a5d8-4d5e534ff19b
                  payfacAcceptorId: ABC-1234567890
      responses:
        '201':
          description: Created
          content:
            application/hal+json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/createAcceptorResponseResource'
              examples:
                Acceptor registration response:
                  value:
                    id: a8b5949e-c7b5-406d-8770-8052ee14fa46
                    externalId: acceptorId
                    name: acceptorName
                    acceptorPspId: e5a9f851-ef03-4e2e-830b-b1da659dbdde
                    mcc: '5555'
                    businessIncorporatedOn: '2024-01-01'
                    marketplace: false
                    _embedded:
                      state:
                        state: Active
                        _links:
                          self:
                            href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/state
                          acceptor:
                            href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46
                      address:
                        line1: "Hauptstra\xDFe 1"
                        line2: Floor 1
                        postalCode: '12345'
                        city: Berlin
                        country: DE
                        state: Berlin
                        _links:
                          self:
                            href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/address
                          acceptor:
                            href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46
                      legal:
                        registerNumber: '123456789012'
                        taxNumber: '123456789012'
                        vatNumber: EU1234567890
                        _links:
                          self:
                            href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/legal
                          acceptor:
                            href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46
                      shops:
                      - id: f81a8715-29b0-4169-8366-b1a460b59855
                        externalId: shopId
                        name: shopName
                        websiteUrl: https://shopName.de
                        tacAndRefundPoliciesUrl: https://shopname.de/terms-and-conditions
                        type: OnlineShop
                        _embedded:
                          state:
                            state: Active
                            _links:
                              self:
                                href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/shops/f81a8715-29b0-4169-8366-b1a460b59855/state
                              shop:
                                href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/shops/f81a8715-29b0-4169-8366-b1a460b59855
                          customerService:
                            emailAddress: customerService@shopname.de
                            contactFormUrl: https://shopname.de/contactUs
                            phoneNumber: '+123456789'
                            _links:
                              self:
                                href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/shops/f81a8715-29b0-4169-8366-b1a460b59855/customer-service
                              shop:
                                href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/shops/f81a8715-29b0-4169-8366-b1a460b59855
                          businessAddress:
                            line1: "Hauptstra\xDFe 1"
                            line2: Floor 1
                            postalCode: '12345'
                            city: Berlin
                            country: DE
                            state: Berlin
                            _links:
                              self:
                                href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/shops/f81a8715-29b0-4169-8366-b1a460b59855/business-address
                              shop:
                                href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/shops/f81a8715-29b0-4169-8366-b1a460b59855
                          disputesContact:
                            personName: John Doe
                            personEmailAddress: john.doe@shopname.de
                            _links:
                              self:
                                href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/shops/f81a8715-29b0-4169-8366-b1a460b59855/disputes-contact
                              shop:
                                href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/shops/f81a8715-29b0-4169-8366-b1a460b59855
                        _links:
                          self:
                            href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/shops/f81a8715-29b0-4169-8366-b1a460b59855
                          state:
                            href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/shops/f81a8715-29b0-4169-8366-b1a460b59855/state
                          acceptor:
                            href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46
                          customerService:
                            href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/shops/f81a8715-29b0-4169-8366-b1a460b59855/customer-service
                          disputesContact:
                            href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/shops/f81a8715-29b0-4169-8366-b1a460b59855/disputes-contact
                          businessAddress:
                            href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/shops/f81a8715-29b0-4169-8366-b1a460b59855/business-address
                          logo:
                            href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/logo
                    _links:
                      self:
                        href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46
                      shops:
                        href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/shops
                      state:
                        href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/state
                      address:
                        href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/address
                      legal:
                        href: http://localhost/api/acceptors/a8b5949e-c7b5-406d-8770-8052ee14fa46/legal
        '400':
          $ref: '#/components/responses/errorResponse400'
        '401':
          $ref: '#/components/responses/errorResponse401'
        '403':
          $ref: '#/components/responses/errorResponse403'
        '409':
          $ref: '#/components/responses/errorResponse409'
        '500':
          $ref: '#/components/responses/errorResponse500'
        '502':
          $ref: '#/components/responses/errorResponse502'
        '503':
          $ref: '#/components/responses/errorResponse503'
    get:
      summary: Retrieve all registered acceptor resources [Acceptor PSP]
      description: "## Acceptor resources\nThe acceptor resource collates all information about the acceptor and its shop sub-resources. \nThe `acceptorPspId` in the authentication token is used to correlate\
        \ the acceptor PSP with its acceptor resources. \n## Active/Inactive options\nTo retrieve only the active acceptors, specify the following option:\n- 'state=Active'\nFor inactive acceptors:\n- 'state=Inactive'\n\
        If no query is given, all acceptors that the acceptor PSP has registered will be returned in the response body.\nThe results are limited to 100 entries and are paginated, with a minimum page size\
        \ of 1. For more information, see [Pagination](ref:pagination).\n## Response\nThe endpoint returns a collection resource. It is possible for the collection resource to contain a single entry. If\
        \ there is nothing to retrieve, an empty collection resource will be returned.\n## Scope \nThis endpoint call requires the `acceptor:management` scope."
      parameters:
      - in: query
        name: state
        description: The value that will be used to filter the possible responses. For example `Active`.
        schema:
          type: string
          enum:
          - Active
          - Inactive
      tags:
      - acceptors
      operationId: get-acceptors
      security:
      - BearerAccessToken: []
      responses:
        '200':
          description: OK
          content:
            application/hal+json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/acceptorPagedCollectionResource'
        '400':
          $ref: '#/components/responses/errorResponse400'
        '401':
          $ref: '#/components/responses/errorResponse401'
        '403':
          $ref: '#/components/responses/errorResponse403'
        '404':
          $ref: '#/components/responses/errorResponse404'
        '500':
          $ref: '#/components/responses/errorResponse500'
        '502':
          $ref: '#/components/responses/errorResponse502'
        '503':
          $ref: '#/components/responses/errorResponse503'
components:
  schemas:
    shopStateResource:
      allOf:
      - $ref: '#/components/schemas/updateShopState'
      - type: object
        required:
        - _links
        properties:
          _links:
            type: object
            description: HAL links to related resources.
            required:
            - self
            - shop
            properties:
              self:
                $ref: '#/components/schemas/link'
              shop:
                $ref: '#/components/schemas/link'
    shopResource:
      type: object
      required:
      - id
      - externalId
      - name
      - _links
      - _embedded
      properties:
        id:
          description: The ID of the shop.
          type: string
          readOnly: true
        externalId:
          description: The external ID of the shop.
          type: string
        name:
          description: The commercial trade name of the shop.
          type: string
        websiteUrl:
          description: The URL of the shop. Must be a valid URL and the scheme must be https.
          type: string
        tacAndRefundPoliciesUrl:
          description: The URL of the terms and conditions and refund policies.
          type: string
        payconiqInvoicePaymentProfileId:
          description: The ID of the Payconiq invoice payment profile, used to pay Payconiq invoice QR codes.
          type: string
          example: ABCDEDFGHI01234567891234
        weroInvoiceQRCodeId:
          description: A public identifier for the shop that can be used to create Wero invoice QR codes. This field is generated by EPI central services when the shop is created if its parent acceptor
            has a `qrCodeCallbackUrl` defined.
          type: string
          example: aBcD1234
        weroStaticQRCodeId:
          description: A public identifier for the shop that can be used to create a Wero static QR code. This field is generated by EPI central services when the `weroStaticQRCodePage` submission has been
            approved.
          type: string
          example: a1B2c3D4
        weroStaticQRCodePage:
          $ref: '#/components/schemas/weroStaticQRCodePageResource'
        type:
          description: The type of shop.
          enum:
          - OnlineShop
          - PointOfSale
          - Hybrid
        _links:
          type: object
          description: The HAL links to related resources.
          required:
          - self
          - state
          - acceptor
          - customerService
          - disputesContact
          - businessAddress
          properties:
            self:
              $ref: '#/components/schemas/link'
            state:
              $ref: '#/components/schemas/link'
            acceptor:
              $ref: '#/components/schemas/link'
            customerService:
              $ref: '#/components/schemas/link'
            disputesContact:
              $ref: '#/components/schemas/link'
            businessAddress:
              $ref: '#/components/schemas/link'
            logo:
              $ref: '#/components/schemas/link'
        _embedded:
          type: object
          required:
          - state
          properties:
            state:
              $ref: '#/components/schemas/shopStateResource'
            customerService:
              $ref: '#/components/schemas/customerServiceResource'
            disputesContact:
              $ref: '#/components/schemas/disputesContactResource'
            businessAddress:
              $ref: '#/components/schemas/businessAddressResource'
    createShopRequest:
      type: object
      required:
      - externalShopId
      - state
      - name
      properties:
        externalShopId:
          description: The external ID of the shop.
          type: string
          minLength: 1
          maxLength: 36
        name:
          description: The commercial trade name of the shop.
          type: string
          minLength: 1
          maxLength: 70
        websiteUrl:
          description: The URL of the shop. Must be a valid URL and the scheme must be https.
          type: string
          minLength: 1
          maxLength: 2000
        logo:
          description: 'The base64-encoded string of the logo in data-URI format. Input images must be in PNG, JPEG (at least 1024x1024px), or SVG format, with a square aspect ratio. The maximum allowed
            file size is 100KB.

            '
          type: string
          example: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgM.....FXgq8FXgq8FXgq8FXgq7fmlf//Z
        tacAndRefundPoliciesUrl:
          description: The URL of the terms and conditions and refund policies.
          type: string
          minLength: 1
          maxLength: 2000
        payconiqInvoicePaymentProfileId:
          description: The ID of the Payconiq invoice payment profile, used to pay Payconiq invoice QR codes.
          type: string
          minLength: 24
          maxLength: 24
          example: ABCDEDFGHI01234567891234
        weroStaticQRCodePage:
          $ref: '#/components/schemas/weroStaticQRCodePageRequest'
        type:
          description: The type of shop.
          enum:
          - OnlineShop
          - PointOfSale
          - Hybrid
          minLength: 3
          maxLength: 255
        state:
          description: The state of the shop.
          type: string
          enum:
          - Active
          - Inactive
          minLength: 3
          maxLength: 255
        customerService:
          $ref: '#/components/schemas/updateCustomerService'
        disputesContact:
          $ref: '#/components/schemas/updateDisputesContact'
        businessAddress:
          $ref: '#/components/schemas/updateBusinessAddress'
    CountryCode:
      title: Country code
      description: A country code in ISO 3166-1 alpha-2 format.
      type: string
      pattern: ^[A-Z]{2}$
      enum:
      - AF
      - AX
      - AL
      - DZ
      - AS
      - AD
      - AO
      - AI
      - AQ
      - AG
      - AR
      - AM
      - AW
      - AU
      - AT
      - AZ
      - BS
      - BH
      - BD
      - BB
      - BY
      - BE
      - BZ
      - BJ
      - BM
      - BT
      - BO
      - BQ
      - BA
      - BW
      - BV
      - BR
      - IO
      - BN
      - BG
      - BF
      - BI
      - CV
      - KH
      - CM
      - CA
      - KY
      - CF
      - TD
      - CL
      - CN
      - CX
      - CC
      - CO
      - KM
      - CG
      - CD
      - CK
      - CR
      - CI
      - HR
      - CU
      - CW
      - CY
      - CZ
      - DK
      - DJ
      - DM
      - DO
      - EC
      - EG
      - SV
      - GQ
      - ER
      - EE
      - ET
      - FK
      - FO
      - FJ
      - FI
      - FR
      - GF
      - PF
      - TF
      - GA
      - GM
      - GE
      - DE
      - GH
      - GI
      - GR
      - GL
      - GD
      - GP
      - GU
      - GT
      - GG
      - GN
      - GW
      - GY
      - HT
      - HM
      - VA
      - HN
      - HK
      - HU
      - IS
      - IN
      - ID
      - IR
      - IQ
      - IE
      - IM
      - IL
      - IT
      - JM
      - JP
      - JE
      - JO
      - KZ
      - KE
      - KI
      - KP
      - KR
      - KW
      - KG
      - LA
      - LV
      - LB
      - LS
      - LR
      - LY
      - LI
      - LT
      - LU
      - MO
      - MK
      - MG
      - MW
      - MY
      - MV
      - ML
      - MT
      - MH
      - MQ
      - MR
      - MU
      - YT
      - MX
      - FM
      - MD
      - MC
      - MN
      - ME
      - MS
      - MA
      - MZ
      - MM
      - NA
      - NR
      - NP
      - NL
      - NC
      - NZ
      - NI
      - NE
      - NG
      - NU
      - NF
      - MP
      - 'NO'
      - OM
      - PK
      - PW
      - PS
      - PA
      - PG
      - PY
      - PE
      - PH
      - PN
      - PL
      - PT
      - PR
      - QA
      - RE
      - RO
      - RU
      - RW
      - BL
      - SH
      - KN
      - LC
      - MF
      - PM
      - VC
      - WS
      - SM
      - ST
      - SA
      - SN
      - RS
      - SC
      - SL
      - SG
      - SX
      - SK
      - SI
      - SB
      - SO
      - ZA
      - GS
      - SS
      - ES
      - LK
      - SD
      - SR
      - SJ
      - SZ
      - SE
      - CH
      - SY
      - TW
      - TJ
      - TZ
      - TH
      - TL
      - TG
      - TK
      - TO
      - TT
      - TN
      - TR
      - TM
      - TC
      - TV
      - UG
      - UA
      - AE
      - GB
      - US
      - UM
      - UY
      - UZ
      - VU
      - VE
      - VN
      - VG
      - VI
      - WF
      - EH
      - YE
      - ZM
      - ZW
      example: DE
    MerchantCategoryCode:
      type: string
      maxLength: 4
      minLength: 4
      pattern: ^\d{4}$
      description: ISO 18245:2023 defines a merchant category code (MCC) as "a code used to classify the business entity by type of activity in which it is engaged, to facilitate the evaluation of various
        risks undertaken by the entity and to better identify its transaction patterns and characteristics." The MCC is a four-digit number that is assigned to a business by credit card companies (for example,
        MasterCard or VISA) when the business first starts to accept one of these cards as a form of payment.
      example: '5812'
    updateBusinessAddress:
      allOf:
      - $ref: '#/components/schemas/AddressInternational'
      - type: object
        required:
        - country
        title: Shop Address
        description: 'The address of the shop. If a shop has multiple branches, every branch is expected to have its own shop resource.

          '
    EuropeanVatNumber:
      title: European VAT number.
      type: string
      pattern: ^[A-Z]{2}[0-9]{2,13}$
      minLength: 4
      maxLength: 15
      description: The full identifier starts with an ISO 3166-1 alpha-2 (2 letters) country code (except for Greece, which uses EL; and Northern Ireland, which uses the code XI) and then has between 2
        and 13 characters.
      examples:
      - EU123456789
    createAcceptorResponseResource:
      allOf:
      - $ref: '#/components/schemas/acceptorResource'
      - type: object
        required:
        - _embedded
        properties:
          _embedded:
            type: object
            required:
            - shops
            properties:
              shops:
                type: array
                description: The list of shops that have been created.
                items:
                  $ref: '#/components/schemas/shopResource'
    weroStaticQRCodePageRedirectionResource:
      type: object
      description: 'The redirect URL points to a web page owned by the acceptor PSP / acceptor, used to initiate a commercial payment in the context of a static Wero QR code.

        The submission of such URL needs to be reviewed by EPI before being approved and used.'
      required:
      - type
      properties:
        type:
          type: string
          enum:
          - redirection
          const: redirection
        redirectUrl:
          type: string
          format: uri
          description: The approved redirect URL
        redirectUrlInReview:
          type: string
          format: uri
          description: The submitted redirect URL, in review by EPI
    updateCustomerService:
      type: object
      properties:
        phoneNumber:
          type: string
          description: The phone number of the customer service contact. The phone number must be a valid mobile phone number in the E.164 format.
          example: '+49712837192318'
          minLength: 3
          maxLength: 16
        emailAddress:
          type: string
          minLength: 6
          maxLength: 255
          description: The e-mail address of the customer service contact.
          format: email
          pattern: ^(.+)@(\S+)$
          example: email@example.com
        contactFormUrl:
          description: The URL of the contact form for customer service.
          type: string
          minLength: 1
          maxLength: 2000
    acceptorPagedCollectionResource:
      type: object
      title: Paged Collection Resource
      required:
      - _embedded
      - _links
      - page
      properties:
        _embedded:
          type: object
          required:
          - acceptors
          properties:
            acceptors:
              type: array
              items:
                $ref: '#/components/schemas/acceptorResource'
        _links:
          type: object
          required:
          - self
          - first
          - last
          properties:
            self:
              $ref: '#/components/schemas/link'
            first:
              $ref: '#/components/schemas/link'
            prev:
              $ref: '#/components/schemas/link'
            next:
              $ref: '#/components/schemas/link'
            last:
              $ref: '#/components/schemas/link'
        page:
          $ref: '#/components/schemas/page'
    updateShopState:
      type: object
      required:
      - state
      properties:
        state:
          description: The state of the shop.
          type: string
          enum:
          - Active
          - Inactive
          minLength: 3
          maxLength: 255
    ConstraintViolationProblem:
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: A URI reference that uniquely identifies the problem type only in the context of the provided endpoint.
          const: /problem/constraint-violation
        title:
          type: string
          description: A short, human-readable summary of the problem type.
          default: Constraint Violation
        status:
          type: integer
          format: int32
          description: The 'status' member is only advisory; it conveys the HTTP status code used for the convenience of the consumer. This attribute is always the same as the status code in the actual
            HTTP response.
          default: 400
        callId:
          type: string
          description: A call ID that identifies the specific occurrence of the problem.
          example: 00000000000000000000000000000000-0000000000000000
        violations:
          type: array
          description: A list of constraint violations.
          items:
            type: object
            required:
            - field
            - message
            properties:
              field:
                type: string
                description: The name of the field that caused the constraint violation.
              message:
                type: string
                description: A technical message that describes the constraint violation, in English.
              userMessageKey:
                type: string
                description: A key that describes the type of constraint violation, useful to report user input validation error. The key can be used to look up a localised message for instance, that can
                  then be interpolated using the `userMessageValue`.
                example: constraint.string.min-length
                oneOf:
                - type: string
                  title: Standard constraint violation key
                  description: 'All known standard constraint violation keys: * **constraint.required**: The field is required. * **constraint.type**: The field must be of the correct type. * **constraint.enum**:
                    The field must be one of the allowed values. `userMessageValue` contains the list as a string value. * **constraint.const**: The field must be a specific value. `userMessageValue` contains
                    the value as a string value. * **constraint.number.multiple-of**: The field must be a multiple of a specific number. `userMessageValue` contains the number as a string value. * **constraint.number.maximum-inclusive**:
                    The field must be less than or equal to a specific number. `userMessageValue` contains the number as a string value. * **constraint.number.maximum-exclusive**: The field must be less
                    than a specific number. `userMessageValue` contains the number as a string value. * **constraint.number.minimum-inclusive**: The field must be greater than or equal to a specific number.
                    `userMessageValue` contains the number as a string value.            * **constraint.number.minimum-exclusive**: The field must be greater than a specific number. `userMessageValue` contains
                    the number as a string value. * **constraint.string.max-length**: The field must be at most a specific number of characters long. `userMessageValue` contains the number as a string value.
                    * **constraint.string.min-length**: The field must be at least a specific number of characters long. `userMessageValue` contains the number as a string value. * **constraint.string.min-length-not-blank**:
                    The field must be at least a specific number of characters long and not blank. `userMessageValue` contains the number as a string value. * **constraint.string.max-graphemes**: The field
                    must be at most a specific number of graphemes long. `userMessageValue` contains the number as a string value. * **constraint.string.pattern**: The field must match a specific pattern.
                    * **constraint.string.length**: The field must be a specific number of characters long. `userMessageValue` contains the number as a string value. * **constraint.string.url**: The field
                    must be a valid URL. * **constraint.string.url-https**: The field must be a valid HTTPS URL. * **constraint.string.uuid4**: The field must be a valid UUID v4. * **constraint.string.email**:
                    The field must be a valid email address. * **constraint.string.phone-number**: The field must be a valid phone number. * **constraint.duration.min-seconds**: The field must be at least
                    a specific number of seconds long. `userMessageValue` contains the number as a string value. * **constraint.duration.max-days**: The field must be at most a specific number of days long.
                    `userMessageValue` contains the number as a string value. * **constraint.datetime.before**: The field must be before a specific date and time. `userMessageValue` contains the `datetime`
                    as a timestamp string value. * **constraint.array.min-items**: The field must contain at least a specific number of items. `userMessageValue` contains the number as a string value. *
                    **constraint.array.max-items**: The field must contain at most a specific number of items. `userMessageValue` contains the number as a string value. * **constraint.array.unique-items**:
                    The field must contain only unique items. * **constraint.amount.maximum**: The field must be less than or equal to a specific amount. * **constraint.amount.minimum**: The field must
                    be greater than or equal to a specific amount. * **constraint.currency-supported**: The field must be a supported currency.'
                  enum:
                  - constraint.required
                  - constraint.type
                  - constraint.enum
                  - constraint.const
                  - constraint.number.multiple-of
                  - constraint.number.maximum-inclusive
                  - constraint.number.maximum-exclusive
                  - constraint.number.minimum-inclusive
                  - constraint.number.minimum-exclusive
                  - constraint.string.max-length
                  - constraint.string.min-length
                  - constraint.string.min-length-not-blank
                  - constraint.string.max-graphemes
                  - constraint.string.pattern
                  - constraint.string.length
                  - constraint.string.url
                  - constraint.string.url-https
                  - constraint.string.uuid4
                  - constraint.string.email
                  - constraint.string.phone-number
                  - constraint.duration.min-seconds
                  - constraint.duration.max-days
                  - constraint.datetime.before
                  - constraint.array.min-items
                  - constraint.array.max-items
                  - constraint.array.unique-items
                  - constraint.amount.maximum
                  - constraint.amount.minimum
                  - constraint.currency-supported
                - type: string
                  description: Placeholder for a future user message key.
                  title: Placeholder for future message keys
                  not:
                    enum:
                    - constraint.required
                    - constraint.type
                    - constraint.enum
                    - constraint.const
                    - constraint.number.multiple-of
                    - constraint.number.maximum-inclusive
                    - constraint.number.maximum-exclusive
                    - constraint.number.minimum-inclusive
                    - constraint.number.minimum-exclusive
                    - constraint.string.max-length
                    - constraint.string.min-length
                    - constraint.string.min-length-not-blank
                    - constraint.string.max-graphemes
                    - constraint.string.pattern
                    - constraint.string.length
                    - constraint.string.url
                    - constraint.string.url-https
                    - constraint.string.uuid4
                    - constraint.string.email
                    - constraint.string.phone-number
                    - constraint.duration.min-seconds
                    - constraint.duration.max-days
                    - constraint.datetime.before
                    - constraint.array.min-items
                    - constraint.array.max-items
                    - constraint.array.unique-items
                    - constraint.amount.maximum
                    - constraint.amount.minimum
                    - constraint.currency-supported
              userMessageValue:
                type: string
                description: A string value that can be used to replace a placeholder in the localised message.
      required:
      - type
      - title
      - status
      - violations
    weroStaticQRCodePageRedirectionRequest:
      type: object
      description: 'Use this type when the target web page of a Wero static QR code belongs to the acceptor PSP / acceptor.

        The `redirectUrl` points to that web page that initiates a commercial payment.

        The submission of the `redirectUrl` will be reviewed by EPI to be either approved or rejected.

        Once the submission has been approved, a `weroStaticQRCodeId` will be provided in the shop resource, ready to be used to generate a Wero static QR code.'
      required:
      - type
      - redirectUrl
      properties:
        type:
          type: string
          enum:
          - redirection
          const: redirection
        redirectUrl:
          type: string
          format: uri
          description: An HTTPS link
    Problem:
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: A URI reference that uniquely identifies the problem type, only in the context of the provided endpoint.
          default: about:blank
          example: /some/uri-reference
          not:
            enum:
            - /problem/constraint-violation
        title:
          type: string
          description: A short, human-readable summary of the problem type.
          example: some title for the error situation
        status:
          type: integer
          format: int32
          description: The 'status' member is only advisory; it conveys the HTTP status code used for the convenience of the consumer. This attribute is always the same as the status code in the actual
            HTTP response.
          minimum: 100
          maximum: 599
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem, which helps locate the problem and describes how to proceed.
          example: some description for the error situation
        instance:
          type: string
          format: uri-reference
          description: A URI reference that identifies the specific occurrence of the problem, for example, by adding a fragment identifier or sub-path to the problem type. Can be used to locate the root
            of the problem in the source code.
          example: /some/uri-reference#specific-occurrence-context
        callId:
          type: string
          description: A call ID that identifies the specific occurrence of the problem.
          example: 00000000000000000000000000000000-0000000000000000
      required:
      - type
      - title
      - status
    customerServiceResource:
      allOf:
      - $ref: '#/components/schemas/updateCustomerService'
      - type: object
        required:
        - _links
        properties:
          _links:
            type: object
            description: HAL links to related resources.
            required:
            - self
            - shop
            properties:
              self:
                $ref: '#/components/schemas/link'
              shop:
                $ref: '#/components/schemas/link'
    createAcceptorRequest:
      type: object
      required:
      - externalId
      - name
      - mcc
      - state
      - address
      properties:
        externalId:
          description: The external ID of the acceptor.
          type: string
          minLength: 1
          maxLength: 36
        name:
          description: The company's legal name.
          type: string
          minLength: 1
          maxLength: 70
        mcc:
          $ref: '#/components/schemas/MerchantCategoryCode'
          description: 'The merchant category code (MCC) of the acceptor. See ISO 18245:2023 for more information on available merchant category codes.

            '
        marketplace:
          description: Whether the acceptor is a marketplace. Marketplaces are electronic commerce platforms where vendors come together to provide goods or services to consumers, for example, eBay. Marketplaces
            must have a contract with an EPI acceptor PSP to offer EPI Products to acceptors. If set to `true`, the acceptor is marked as a marketplace.
          type: boolean
          default: false
        state:
          description: The state of the acceptor.
          type: string
          enum:
          - Active
          - Inactive
          minLength: 3
          maxLength: 255
        businessIncorporatedOn:
          description: The date that the acceptor's business was created.
          type: string
          format: date
          example: '2023-12-21'
        qrCodeCallbackUrl:
          description: The URL that will be used to initiate consent-based payments based on scanned QR codes.
          type: string
          minLength: 1
          maxLength: 2000
          format: uri
          example: https://acceptorPSP.com/offline-qr-code/pay
        address:
          $ref: '#/components/schemas/updateAddress'
        legal:
          $ref: '#/components/schemas/updateLegal'
        shops:
          type: array
          items:
            $ref: '#/components/schemas/createShopRequest'
        payfacId:
          description: When the acceptor is managed by a payment facilitator, the ID of the payment facilitator in EPI central services.
          type: string
          format: uuid
        payfacAcceptorId:
          description: When the acceptor is managed by a payment facilitator, the ID of the acceptor within the payment facilitator's system.
          type: string
          minLength: 1
          maxLength: 300
    page:
      type: object
      examples:
      - size: 1
        totalElements: 1
        totalPages: 1
        number: 0
        requestedPageSize: 10
        limitReached: false
      properties:
        size:
          type: integer
          description: The number of elements on the page.
        totalElements:
          type: integer
          description: The total number of elements available with the query.
        totalPages:
          type: integer
          description: The total number of pages available, using the requested page size.
        number:
          type: integer
          description: The number of the current page. Page numbers start at `0` and continue to the total number of pages.
        requestedPageSize:
          type: integer
          description: The requested page size. The value of "size" might differ for the last page if the last page is not full.
        limitReached:
          type: boolean
          description: If `true`, an internal limit when retrieving results was exceeded. Not all elements are returned.
      description: A paginated resource is a HAL resource. The resource contains the page object, which describes the provided subset of data. The data is provided as an embedded collection resource. The
        name of the collection depends on the endpoint. HAL links are also provided, for navigation.
      title: Structure of a paginated response
      required:
      - size
      - totalElements
      - totalPages
      - number
      - requestedPageSize
      - limitReached
    disputesContactResource:
      allOf:
      - $ref: '#/components/schemas/updateDisputesContact'
      - type: object
        required:
        - _links
        properties:
          _links:
            type: object
            description: HAL links to related resources.
            required:
            - self
            - shop
            properties:
              self:
                $ref: '#/components/schemas/link'
              shop:
                $ref: '#/components/schemas/link'
    businessAddressResource:
      allOf:
      - $ref: '#/components/schemas/updateBusinessAddress'
      - type: object
        required:
        - _links
        properties:
          _links:
            type: object
            description: HAL links to related resources.
            required:
            - self
            - shop
            properties:
              self:
                $ref: '#/components/schemas/link'
              shop:
                $ref: '#/components/schemas/link'
    updateAddress:
      allOf:
      - $ref: '#/components/schemas/AddressInternational'
      - type: object
        required:
        - country
        title: Acceptor Address
        description: 'The address of the headquarters of the acceptor.

          '
    legalResource:
      allOf:
      - $ref: '#/components/schemas/updateLegal'
      - type: object
        required:
        - _links
        properties:
          _links:
            type: object
            description: HAL links to related resources.
            required:
            - self
            - acceptor
            properties:
              self:
                $ref: '#/components/schemas/link'
              acceptor:
                $ref: '#/components/schemas/link'
    weroStaticQRCodePageRequest:
      type: object
      description: Definition of the page that should be opened by a Wero wallet app once a Wero static QR code is decoded.
      discriminator:
        propertyName: type
        mapping:
          redirection: '#/components/schemas/weroStaticQRCodePageRedirectionRequest'
      oneOf:
      - $ref: '#/components/schemas/weroStaticQRCodePageRedirectionRequest'
    AddressInternational:
      title: International Address
      type: object
      description: An international address.
      required: []
      properties:
        line1:
          type: string
          description: Line of the address (e.g. street name and number).
          minLength: 1
          maxLength: 255
        line2:
          type: string
          description: Additional line for the address (e.g. apartment, suite, unit, building, floor, etc.).
          minLength: 1
          maxLength: 255
        postalCode:
          type: string
          description: The postal code.
          minLength: 1
          maxLength: 12
        city:
          type: string
          minLength: 1
          maxLength: 100
        country:
          type: string
          description: The country code (ISO 3166-1 alpha-2).
          minLength: 2
          maxLength: 2
          $ref: '#/components/schemas/CountryCode'
        state:
          type: string
          description: State or province for the address.
          minLength: 1
          maxLength: 255
      example:
        line1: Some street St 1
        line2: Apartment 1, suite 3, floor 1
        postalCode: '48180'
        city: Madrid
        country: ES
        state: Madrid
    link:
      type: object
      properties:
        href:
          type: string
          format: uri
        name:
          type: string
      required:
      - href
    updateDisputesContact:
      type: object
      properties:
        personEmailAddress:
          type: string
          minLength: 6
          maxLength: 255
          description: The e-mail address of the disputes contact.
          format: email
          pattern: ^(.+)@(\S+)$
          example: email@example.com
        personName:
          description: The name of the disputes contact person.
          type: string
          minLength: 1
          maxLength: 300
    weroStaticQRCodePageResource:
      type: object
      description: Definition of the page that should be opened by a Wero wallet app once a Wero static QR code is decoded.
      discriminator:
        propertyName: type
        mapping:
          redirection: '#/components/schemas/weroStaticQRCodePageRedirectionResource'
      oneOf:
      - $ref: '#/components/schemas/weroStaticQRCodePageRedirectionResource'
    stateResource:
      allOf:
      - $ref: '#/components/schemas/updateState'
      - type: object
        required:
        - _links
        properties:
          _links:
            type: object
            description: HAL links to related resources.
            required:
            - self
            - acceptor
            properties:
              self:
                $ref: '#/components/schemas/link'
              acceptor:
                $ref: '#/components/schemas/link'
    acceptorResource:
      type: object
      required:
      - id
      - externalId
      - name
      - acceptorPspId
      - mcc
      - _embedded
      - _links
      properties:
        id:
          description: ID of the acceptor that EPI central services provide when creating the acceptor resource.
          type: string
          format: uuid
          readOnly: true
        externalId:
          description: The external ID of the acceptor.
          type: string
        name:
          description: The company's legal name.
          type: string
        acceptorPspId:
          description: The ID of the acceptor PSP.
          type: string
          readOnly: true
        payfacId:
          description: When the acceptor is affiliated to a payment facilitator, this is the ID of the payment facilitator in EPI central services.
          type: string
          readOnly: true
        payfacAcceptorId:
          description: When the acceptor is affiliated to a payment facilitator, this is the ID of the acceptor in the payment facilitator system.
          type: string
          readOnly: true
        mcc:
          $ref: '#/components/schemas/MerchantCategoryCode'
          description: "The merchant category code (MCC) of the acceptor. See ISO 18245:2023 for more information on available merchant category codes.    \n"
        marketplace:
          description: Whether the acceptor is a marketplace. Marketplaces are electronic commerce platforms where vendors come together to provide goods or services to consumers, for example, eBay. Marketplaces
            must have a contract with an EPI acceptor PSP to offer EPI Products to acceptors. If `marketplace` has the value set to `true`, the acceptor is marked as a marketplace.
          type: boolean
        businessIncorporatedOn:
          description: The date that the acceptor's business was created.
          type: string
          format: date
          example: '2023-12-21'
        qrCodeCallbackUrl:
          description: The URL that will be used to initiate consent-based payments based on scanned QR codes.
          type: string
          format: uri
          example: https://acceptorPSP.com/offline-qr-code/pay
        _embedded:
          type: object
          required:
          - state
          - address
          - legal
          properties:
            state:
              $ref: '#/components/schemas/stateResource'
            address:
              $ref: '#/components/schemas/addressResource'
            legal:
              $ref: '#/components/schemas/legalResource'
        _links:
          type: object
          description: The HAL links to related resources.
          required:
          - self
          - shops
          - state
          - address
          - legal
          properties:
            self:
              $ref: '#/components/schemas/link'
            shops:
              $ref: '#/components/schemas/link'
            state:
              $ref: '#/components/schemas/link'
            address:
              $ref: '#/components/schemas/link'
            legal:
              $ref: '#/components/schemas/link'
    updateLegal:
      type: object
      description: The information that public administration and regulators provide and require to manage an acceptor.
      properties:
        vatNumber:
          allOf:
          - $ref: '#/components/schemas/EuropeanVatNumber'
            description: The company VAT number that EPI requires to bill acceptors.
        taxNumber:
          type: string
          description: Company tax number.
          example: '123456789012'
          minLength: 1
          maxLength: 255
        registerNumber:
          type: string
          description: Company registration number.
          example: '123456789012'
          minLength: 1
          maxLength: 255
    updateState:
      type: object
      required:
      - state
      properties:
        state:
          description: State of the acceptor.
          type: string
          enum:
          - Active
          - Inactive
          minLength: 3
          maxLength: 255
    addressResource:
      allOf:
      - $ref: '#/components/schemas/AddressInternational'
      - type: object
        required:
        - _links
        - country
        properties:
          _links:
            type: object
            description: HAL links to related resources.
            required:
            - self
            - acceptor
            properties:
              self:
                $ref: '#/components/schemas/link'
              acceptor:
                $ref: '#/components/schemas/link'
